l_english:
  SETTING_DEBUG_SAVES: "Кількість збережень налагодження"
  SETTING_TUTORIAL: "Навчання"
  SETTING_DISABLED_HINTS: "Вимкнені підказки"
  SETTING_FOCUS_ON_COMBAT: "Фокус на битві"
  SETTING_TOOLTIP_DELAY: "Затримка підказок"
  SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nЗатримка між появою підказок."
  SETTING_TOOLTIP_UNLOCK_TIME: "Затримка розблокування"
  SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nЗатримка перед розблокуванням підказок."
  SETTING_TOOLTIP_LOCK_TIME: "Затримка блокування"
  SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nЗатримка перед блокуванням підказок."
  SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Затримка відкриття"
  SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nЗатримка перед блокуванням підказок, якщо одна підказка вже відкрита."
  # Audio
  SETTING_Sound_Effects: "Всі звукові ефекти"
  SETTING_Sound_Effects_TOOLTIP: "#T Звукові ефекти\n#!Встановлює гучність всіх звукових ефектів."
  SETTING_Ambience: "Оточення"
  SETTING_Ambience_TOOLTIP: "#T Гучність оточення\n#!Встановлює гучність звуків оточення."
  SETTING_TOOLTIP_MODE: "Режим підказок"
  SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nВстановлює посіб фіксації підказок — вмикає підказки в підказках."
  SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Поведінка мишки"
  SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nПідказки автоматично фіксуються, поки ви не приберете з них курсор мишки."
  SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Ручне блокування"
  SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nНатисніть #V середню кнопку мишки#!, щоб заблокувати або розблоковувати підказку."
  SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Увімкнення таймера"
  SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nПідказки залишаються на місці, якщо курсор мишки протягом короткого часу залишається нерухомим. #weak (Типово)#!"
  SETTINGS_CATEGORY_INTERFACE_MISC: "Різне"
  SETTINGS_CATEGORY_TOOLTIPS: "Підказки"
  SETTINGS_CATEGORY_SFX: "Спеціальні звукові ефекти"
  SETTINGS_CATEGORY_AUDIO_GENERAL: "Загальні"
  SETTINGS_CATEGORY_MAP_CONTROLS: "Керування картою"
  SETTINGS_CATEGORY_SAVE_GAMES: "Збереження гри"
  SETTINGS_CATEGORY_LANGUAGE: "Мова"
  SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Додаткові налаштування"
  SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "Advanced – Map"
  SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "Advanced – Characters"
  SETTINGS_CATEGORY_GAME_PORTRAITS: "Портрети"
  SETTINGS_CATEGORY_MULTIPLAYER: "Мережева гра"
  SETTINGS_CATEGORY_MAP: "Мапа"
  SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Показувати реалістичні рани та сліди від хвороб"
  SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nВизначає, чи на портретах персонажів з'являтимуться реалістичні рани та сліди від хвороб."
  SETTING_SHOW_NUDITY: "Показувати оголеність"
  SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nSets whether characters can be shown nude."
  SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "Royal Court Idle Pan"
  SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nDetermines if the camera in the Royal Court should pan gently across your Court when idle.\n\nIf Animated Characters is turned off, this setting has no effect."
  SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "Royal Court Smooth Transitions"
  SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nDetermines if the camera in the Royal Court should move smoothly to a new location.\n\nIf Animated Characters is turned off, this setting has no effect."
  NEVER: "Ніколи"
  MONTHLY: "Щомісяця"
  HALFYEAR: "Кожні 6 місяців"
  YEARLY: "Щороку"
  FIVE_YEAR: "Кожні 5 років"
  SETTINGS_CATEGORY_TUTORIAL: "Навчання"
  SETTING_REACTIVE_TUTORIAL: "Показувати контекстні поради"
  SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nУвімкніть або вимікніть поради, які реагують на те, як ви граєте. Вони згодяться новим гравцям в Crusader Kings III."
  SETTING_SHOW_SUGGESTIONS: "Показати пропозиції"
  SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nУвімкніть або вимкніть поради, які з'являтимуться через регулярні проміжки часу. Такі підказки згодяться новим гравцям в Crusader Kings III."
  RESET_REACTIVE_ADVICE: "Скинути контекстні поради"
  RESET_REACTIVE_ADVICE_TOOLTIP: "#T Скинути контекстні поради#!\nКонтекстні поради, які вже були показані, з'являться ще раз."
  RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Скинути контекстні поради"
  RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Ви впевнені, що хочете скинути контекстні поради?"
  SETTING_ADVANCED_SHADERS: "Додаткові ефекти шейдерів"
  SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Додаткові ефекти шейдерів\n#!Цей параметр вмикає додаткові ефекти шейдерів.\n\nПри вимкненні продуктивність системи може вирости, а якість візуальних ефектів (наприклад промальовування ландшафту та води) знизиться."
  SETTING_WINTER_PARTICLE_EFFECTS: "Winter Particle Effects"
  SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDetermines whether particle effects are shown or not when Winter is active in some areas of the map.\n\nTurning it off may increase performance"
  SETTING_RESET_CAMERA_ROTATION: "Camera Rotation Reset"
  SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermines if the camera should automatically reset default position after being rotated by the user"
  SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "Court Scene Background Characters"
  SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermines if the Royal Court 3D scene should display less important background characters."
  SETTING_MAP_HIGHLIGHT: "Map Cursor Highlight"
  SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nВизначає інтенсивність підсвічування курсору на карті"
  BASED_ON_ZOOM_LEVEL: "Динамічні"
  ALWAYS_HIDE: "Завжди приховувати"
  ALWAYS_SHOW: "Завжди показувати"
  SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Берегові кордони"
  SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nЦей параметр управляє відображенням берегових кордонів держави.\n$BASED_ON_ZOOM_LEVEL$ приховує їх на детальній карті.\n\n$ALWAYS_SHOW$ або $ALWAYS_HIDE$ можуть поліпшити продуктивність, але кордони автоматично не ховатимуться при наближенні."
  SETTINGS_DISCARD_CHANGES: "Відмінити зміни"