l_english:
  #General
  SETTING_VALUE_NONE: "$VALUE$"
  SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
  SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
  SETTING_VALUE_SECONDS: "$VALUE$ сек."
  SETTING_VALUE_MINUTES: "$VALUE$ хв."
  #Graphics
  SETTING_RENDERER: "Рендерер"
  SETTING_RENDERER_TOOLTIP: "Визначає, який рендер використовується."
  SETTING_VSYNC: "Вертикальна сихронізація"
  SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Робить у грі та вашому моніторі однакову частоту кадрів, зменшуючи розриви на екрані.\n\nВимкнення може збільшити продуктивність."
  SETTING_PORTRAIT_MULTI_SAMPLING: "Портретне багаторазове згладжування"
  SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Використання кількох зразків для Alpha-To-Coverage для більш гладкого відображення волосся.\n\nНижчі налаштування підвищують продуктивність."
  SETTING_MULTI_SAMPLING: "Згладжування (MSAA)"
  SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!Використання багаторазового згладжування (MSAA) зробить краї зображень більш гладкими.\n\nНижчі налаштування можуть збільшити продуктивність."
  SETTING_ANTI_ALIASING: "Згладжування"
  SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!Використання згладжування зробить краї зображень більш гладкими.\n\nFXAA рекомендується."
  OPTION_ANTI_ALIASING_DISABLED: "Вимкнено"
  OPTION_ANTI_ALIASING_FXAA: "FXAA"
  SETTING_UPSCALE: "Якісний метод"
  OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
  OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
  OPTION_UPSCALE_XESS: "Intel® XeSS"
  SETTING_UPSCALE_QUALITY: "Якість найвищого масштабу"
  OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Надвисока якість"
  OPTION_UPSCALE_QUALITY_QUALITY: "Якість"
  OPTION_UPSCALE_QUALITY_BALANCED: "Збалянсовано"
  OPTION_UPSCALE_QUALITY_PERFORMANCE: "Продуктивність"
  OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Надвисока продуктивність"
  SETTING_ANISOTROPIC_FILTERING: "Фільтрація текстур"
  SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Використання анізотропної фільтрації покращить вигляд текстур.\n\nНижчі налаштування можуть збільшити продуктивність."
  SETTING_FULLSCREEN_RESOLUTION: "Роздільна здатність"
  SETTING_FULLSCREEN_RESOLUTION_TOOLTIP: "\"#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Встановлює якість зображення гри.\n\nНижча роздільна здатність може збільшити продуктивність.\n\n#X Роздільна здатність гри з непідтримуваним співвідношенням сторін може призвести до того, що інтерфейси відображатимуться поза екраном#!"
  SETTING_WINDOWED_RESOLUTION: "Віконна роздільна здатність"
  SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Встановлює роздільну здатність вікна гри, якщо гра знаходиться у віконному режимі.\n\nМає бути у форматі #b NUMBER#!x#b NUMBER#!.\n\n#X Роздільна здатність гри з непідтримуваним співвідношенням сторін може призвести до того, що інтерфейси відображатимуться поза екраном#!"
  SETTING_RENDER_SCALE: "Масштаб візуалізації"
  SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nМасштаб роздільної здатности рендеринґу гри відносно основної роздільної здатности, за винятком інтерфейсу користувача.\n\nНижчі налаштування можуть збільшити продуктивність але зменшить загальну точність, тоді як перевищення на 100% може підвищити точність, але ймовірно погіршить продуктивність."
  SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
  SETTING_DISPLAY: "Монітор"
  SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Якщо ваш комп’ютер має кілька моніторів, виберіть той, який використовуватиме гра."
  SETTING_GRAPHICS_DEVICE: "Відеокарта"
  SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Вибирає, яку відевокарту використовуватиме гра. \n\nВикористання вбудованої відевокарти або програмного рендерера може знизити продуктивність."
  SETTING_SHADOW_MAP_RESOLUTION: "Якість тіней"
  SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Визначає роздільну здатність візуалізації мапи тіней, якщо тіні ввімкнено.\n\nНижчі налаштування можуть збільшити продуктивність."
  SETTING_DISPLAY_MODE: "Режим відображення"
  SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Визначає спосіб відображення гри на екрані"
  SETTING_BLOOM: "Світіння"
  SETTING_MESH_LOD_BIAS: "Якість Mesh LOD"
  SETTING_MESH_LOD_FADE: "Сітка LOD Fade"
  SETTING_TERRAIN_SMOOTHING: "Згладжування рельєфу"
  OPTION_FULLSCREEN: "Повноекранний"
  OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Показати гру на весь екран. Налаштування роздільної здатности змінює чіткість зображення."
  OPTION_WINDOWED: "Вікном"
  OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Відображати гру у вікні. Роздільна здатність змінює розмір вікна."
  OPTION_DISABLED: "Вимкнено"
  OPTION_OFF: "Вимкнено"
  OPTION_LOW: "Низьк."
  OPTION_MEDIUM: "Середн."
  OPTION_HIGH: "Висок."
  OPTION_ULTRA: "Надвисок."
  OPTION_CUSTOM: "Користувацьк."
  OPTION_DEFAULT: "За замовчуванням"
  SETTINGS_CATEGORY_UI: "Інтерфейс"
  SETTINGS_CATEGORY_GAME: "Гра"
  SETTING_TEXTURE_QUALITY: "Якість текстур"
  SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nКерує роздільною здатністю завантажених текстур.\n\nНижчі налаштування можуть збільшити продуктивність."
  SETTING_QUALITY: "Задане налаштування якости"
  SETTING_SFX: "Звукові ефекти"
  SETTING_UI: "Інтерфейс"
  SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Виберіть задане налаштування для розширених параметрів графіки нижче.\n\nНизьке налаштування підвищить продуктивність."
  SETTING_BLOOM_TOOLTIP: "#T $SETTING_BLOOM$\n#!Вмикає блюм ефект, де надзвичайно яскраве світло переливатиметься на інші частини зображення.\n\nВимкнення може збільшити продуктивність."
  SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Вмикає глибину різкості для імітації об’єктива знімача, розмиває точки зображення поза фокусом.\n\nВимкнення може збільшити продуктивність."
  SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Увімкнення ефекту відблиску лінзи, який з‘являється в місцях сильної якскравости. Для того, щоб ефект з‘явився, необхідно увімкнути блюм. \n\nВимкнення може збільшити продуктивність."
  SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Вмикає ефект вторинного відблиску об‘єктива, який з‘являється в місцях сильної якскравости. Для того, щоб ефект з‘явився, необхідно увімкнути блюм. \n\nВимкнення може збільшити продуктивність."
  SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Визначає, чи слід застосувати до мапи затінення навколишнього світла у екранному просторі.\n\nВимкнення може збільшити продуктивність."
  SETTING_REFRACTION_TOOLTIP: "Визначає, чи з‘являються заломлення на воді чи ні."
  SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nКонтролює якість заломлення води, якщо вони включені.\n\nНижчі налаштування можуть збільшити продуктивність."
  SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nВизначає найвищий рівень якости об’єктів мапи (наприклад, будівель).\n\nНижчі налаштування можуть збільшити продуктивність."
  SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nВизначає якість LOD (рівнів деталізації) на об’єктах мапи, таких як моделі одиниць.\n\nНижчі налаштування можуть збільшити продуктивність."
  SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Якщо ввімкнено, 3Д-моделі плавно переходять між різними рівнями деталізації (LOD), коли ви збільшуєте чи зменшуєте розмір.\n\nВимкнення може збільшити продуктивність."
  SETTING_PROVINCE_NAMES_TOOLTIP: "Визначає, як назви міст і провінцій відображаються на мапі."
  SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Визначає, чи входить непрохідна місцевість до кордонів країни на мапі."
  SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nВизначає мову інтерфейсу користувача."
  SETTING_ACCOUNT_EMAIL_TOOLTIP: "Ваша електронна адреса обліковки Парадокс"
  SETTING_FRAMERATE_CAP: "Максимальний FPS"
  SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nМаксимальна кількість кадрів в секунду (FPS), яку візуалізує гра.\n\nНижчі налаштування можуть зменшити споживання електроенергії."
  OPTION_CAP_30: "30"
  OPTION_CAP_60: "60"
  OPTION_CAP_90: "90"
  OPTION_CAP_120: "120"
  OPTION_CAP_144: "144"
  OPTION_CAP_165: "165"
  SETTING_TEXTURE_STREAMING: "Потокове передавання текстур"
  SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nTextures are loaded in as needed.\n\nLowers GPU memory usage at the cost of some CPU time overhead. May increase performance for GPU's with a small amount of memory."
  SETTING_TEXTURE_STREAMING_CACHE: "Розмір кешу потокового передавання текстур"
  SETTING_VALUE_MB: "$VALUE$ Мб"
  #GUI
  SETTING_ANIMATION_SPEED: "Швидкість анімації"
  SETTING_GUI_SCALING: "Масштабування графічного інтерфейсу"
  SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Встановлює мірило усього інтерфейсу користувача. Корисно для вищої роздільної здатності екрана.\n\n#X Якщо встановити занадто високе значення, інтерфейси не будуть належним чином розміщуватися на екрані!#!"
  #System
  SETTING_SCREEN_EDGE_SCROLL_MODE: "Приближення миші"
  SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Вільне"
  SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 напрямків"
  SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Вимкнено"
  SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nЯк поводиться знімач під час панорамування за допомогою миші."
  SETTING_SCROLL_SPEED: "Швидкість приближення"
  SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nВстановлює швидкість приближення мапи при використання клавіятури чи миші."
  SETTING_CAMERA_ROTATION_SPEED: "Швидкість обертання знімача"
  SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nШвидкість обертання знімача."
  SETTING_ZOOM_SPEED: "Швидкість приближення"
  SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nШвидкість збільшення знімача."
  SETTING_MOUSE_CURSOR_ZOOM_MODE: "Поведінка приближення"
  SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Відносно вказівника"
  SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Приблизити до вказівника"
  SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ігнорувати вказівник"
  SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nЯк знімач поводиться відносно вказівника під час приближення/віддалення."
  SETTING_INPUT_DEVICE: "Пристрій введення"
  SETTING_EDITOR: "Редактор"
  SETTING_EDITOR_POSTFIX: "Editor postfix"
  SETTING_EDITOR_OPEN_FILE_FORMAT: "Editor open command"
  SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "View log command"
  SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Code editor open command"
  SETTING_GRACEFUL_EXIT: "Витончений вихід"
  SETTING_LANGUAGE: "Мова"
  MOUSE_AND_KEYBOARD: "Мишка і клавіятура"
  GAMEPAD: "Геймпад"
  SETTING_MULTISAMPLING_DISABLED: "Вимкнено"
  SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Вимкнено"
  SETTING_ANISOTROPIC_FILTERING_DISABLED: "Вимкнено"
  #Editor
  SETTING_CAMERA_TILT: "Camera tilt"
  SETTING_CAMERA_STRATEGY: "Camera type"
  SETTING_CENTERED_ZOOM_IN: "Centered zoom-in"
  SETTING_CAMERA_SPEED: "Швидкість камери"
  CAMERA_TABLETOP: "Table top"
  CAMERA_FPS: "First person"
  CAMERA_WASD: "WASD-style"
  #Audio
  SETTING_Music: "Музика"
  SETTING_Ambient: "Довкілля"
  SETTING_Effects: "Ефекти"
  SETTING_Master: "Загальне"
  SETTING_VO: "Голосовий супровід"
  SETTING_VO_TOOLTIP: "#T Гучність голосового супроводу\n#!Задає гучність голосового супроводу у грі."
  SETTING_Master_TOOLTIP: "#T Загальна гучність\n#!Встановлює гучність усіх звуків у грі."
  SETTING_Music_TOOLTIP: "#T Гучність музики\n#!Встановлює гучність музики."
  SETTING_Ambient_TOOLTIP: "#T Гучність довкілля\n#!Встановлює гучність довкілля."
  SETTING_SFX_TOOLTIP: "#T Гучність звукових ефектів\n#!Встановлює гучність звукових ефектів, наприклад бою."
  SETTING_UI_TOOLTIP: "#T Гучність інтерфейсу\n#!Встановлює гучність інтерфейсу користувача."
  SETTING_AUDIO_DEBUG_LOG_LEVEL: "Рівень журналу налагодження"
  SETTING_AUDIO_DEVICE_PROFILE: "Звуковий профіль"
  SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Виберіть звуковий профіль, який відповідає вашим налаштуванням."
  SETTING_AUDIO_OPTION_SPEAKERS: "Колонки"
  SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Стандартний мікс для $SETTING_AUDIO_OPTION_SPEAKERS$."
  SETTING_AUDIO_OPTION_HEADPHONES: "Навушники"
  SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Мікс з поправкою на $SETTING_AUDIO_OPTION_HEADPHONES$."
  SETTING_AUDIO_OPTION_TV: "ТБ"
  SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Мікс для $SETTING_AUDIO_OPTION_TV$ і моніторних колонок."
  SETTING_AUDIO_OPTION_NIGHTMODE: "Нічний режим"
  SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Пом’якшує звук для нічної гри, приглушуючи вищі тони та стискаючи динамічний діяпазон."
  SETTING_MUSIC_DENSITY: "Щільність музики"
  SETTING_MUSIC_DENSITY_TOOLTIP: "Контролює балянс між повними піснями, тишею та сегментами настроєвої музики.\n\nІнтенсивна = здебільшого пісні грають одна за одною, подібно до «радіостанції».\nЗбалянсована = ідеальний балянс між піснями, тишею та настроєм.\nРозслаблена = переважно музичні фрагменти, які розслабляють та забезпечують кращий настрій і менше відчуття повторення після кількох годин прослуховування."
  #Game
  SETTING_AUTOSAVE: "Частота самозбереження"
  SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Встановлює частоту самозбереження гри."
  SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Визначає, чи зберігаються самозбереження в хмарі."
  SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Визначає, чи буде знімач завжди спрямована на північ чи ні."
  NO_AUTOSAVE: "Без самозбереження"
  #Multiplayer
  SETTINGS_FILE_TRANSFER_SPEED: "Швидкість передавання файлів"
  SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $SETTINGS_FILE_TRANSFER_SPEED$\n#!Встановлює максимальну швидкість передавання файлів збереження гри в лобі для кількох гравців.\n\nНижчі параметри можуть покращити стабільність мережі під час приєднання до багатокористувацьких ігор, але негативно впливають на час завантаження багатокористувацьких ігор."
  #Tools
  SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Автоматичне збереження редактора мапа (хвилини)"
  SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Частота самозбереження редактора мапа (хвилини)"
  SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Режим перетягування редактора вузлів"
  SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Console auto-complete mode"
  SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Full expand, iterate with tab"
  SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Partial expand until different"
  #Accessibility
  SETTINGS_CATEGORY_ACCESSIBILITY: "Доступність"
  SETTING_COLOR_BLIND_MODE: "Режим дальтоніка"
  SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Змінює кольори, які використовуються в тексті протягом гри, на набір кольорів, який легше розрізняти для різних типів дальтонізму."
